spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  data:
    redis:
      host: "redis"
      port: 6379
      password: "${REDIS_PASSWORD}"

server:
  port: 8080

jwt:
  secret: "${JWT_SECRET}"
  access-token-expiration: "${JWT_ACCESS_EXPIRATION}"
  refresh-token-expiration: "${JWT_REFRESH_EXPIRATION}"

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.jdbc: WARN